/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ochjzjphfzukebmsykkh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jaGp6anBoZnp1a2VibXN5a2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzNTMxMTgsImV4cCI6MjA5MTkyOTExOH0.b_50138o-NBrM1GDfiRhtEjS8dxdghc37-mN-CcU4DI"